/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import datos.*;
import domain.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acmm
 */
public class InterfazUsuario extends javax.swing.JFrame {

    /**
     * Creates new form InterfazUsuario
     */
    public InterfazUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        consulta = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        jCombo = new javax.swing.JComboBox<>();
        busquedaAvanzada = new javax.swing.JButton();
        jComboTipo = new javax.swing.JComboBox<>();
        jComboTalla = new javax.swing.JComboBox<>();
        jComboColor = new javax.swing.JComboBox<>();
        jrZapatos = new javax.swing.JRadioButton();
        jrCamisas = new javax.swing.JRadioButton();
        jrPantalones = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ClothesBook");
        setLocation(new java.awt.Point(520, 300));

        consulta.setText("Productos");
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
            }
        });

        buscar.setText("Buscar ");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        jCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zapatos", "Camisas", "Pantalones" }));
        jCombo.setToolTipText("");

        busquedaAvanzada.setText("Busqueda avanzada");
        busquedaAvanzada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaAvanzadaActionPerformed(evt);
            }
        });

        jComboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoActionPerformed(evt);
            }
        });

        jComboTalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTallaActionPerformed(evt);
            }
        });

        grupo1.add(jrZapatos);
        jrZapatos.setText("Zapatos");
        jrZapatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrZapatosActionPerformed(evt);
            }
        });

        grupo1.add(jrCamisas);
        jrCamisas.setText("Camisas");
        jrCamisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrCamisasActionPerformed(evt);
            }
        });

        grupo1.add(jrPantalones);
        jrPantalones.setText("Pantalones");
        jrPantalones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrPantalonesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboTalla, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(busquedaAvanzada)
                            .addComponent(consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboColor, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jrZapatos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrCamisas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrPantalones)))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addComponent(busquedaAvanzada, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrZapatos)
                    .addComponent(jrCamisas)
                    .addComponent(jrPantalones))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jComboColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID producto", "Tipo", "Talla", "Color", "Marca", "precio", "cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jProductos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jProductos.getModel();
        modelo.setRowCount(0);
        Producto producto = new Producto();
        List<Producto> productos = producto.consulta();
        productos.forEach(consulta -> {
            String[] fila = {"" + consulta.getIdProducto(), "" + consulta.getTipo(), "" + consulta.getTalla(), "" + consulta.getColor(), "" + consulta.getMarca(),
                "" + consulta.getPrecio(), "" + consulta.getCantidad()};
            modelo.addRow(fila);
        });


    }//GEN-LAST:event_consultaActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jProductos.getModel();
        modelo.setRowCount(0);
        String seleccion = jCombo.getSelectedItem().toString();
        switch (seleccion) {
            case "Zapatos":
                ZapatoDao zapatoDao = new ZapatosDaoJdbc();
                List<Zapato> zapatos = zapatoDao.seleccionar();
                zapatos.forEach(consulta -> {
                    String[] fila = {"" + consulta.getIdProducto(), "" + consulta.getTipo(), "" + consulta.getTalla(), "" + consulta.getColor(), "" + consulta.getMarca(),
                        "" + consulta.getPrecio(), "" + consulta.getCantidad()};
                    modelo.addRow(fila);
                });
                break;

            case "Camisas":
                CamisaDao camisaDao = new CamisaDaoJdbc();
                List<Camisa> camisas = camisaDao.seleccionar();
                camisas.forEach(consulta -> {
                    String[] fila = {"" + consulta.getIdProducto(), "" + consulta.getTipo(), "" + consulta.getTalla(), "" + consulta.getColor(), "" + consulta.getMarca(),
                        "" + consulta.getPrecio(), "" + consulta.getCantidad()};
                    modelo.addRow(fila);
                });
                break;

            case "Pantalones":
                PantalonDao pantalonDao = new PantalonDaoJdbc();
                List<Pantalon> pantalones = pantalonDao.seleccionar();
                pantalones.forEach(consulta -> {
                    String[] fila = {"" + consulta.getIdProducto(), "" + consulta.getTipo(), "" + consulta.getTalla(), "" + consulta.getColor(), "" + consulta.getMarca(),
                        "" + consulta.getPrecio(), "" + consulta.getCantidad()};
                    modelo.addRow(fila);
                });
                break;

            default:
                JOptionPane.showMessageDialog(null, "No seleccionaste ninguna opcion de busqueda");
        }


    }//GEN-LAST:event_buscarActionPerformed

    private void busquedaAvanzadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaAvanzadaActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jProductos.getModel();
        modelo.setRowCount(0);
        String seleccion = jCombo.getSelectedItem().toString();
        switch (seleccion) {
            case "Zapatos":
                ZapatoDao zapatoDao = new ZapatosDaoJdbc();
                Zapato zapatoAd = new Zapato(jComboTipo.getSelectedItem().toString(),jComboTalla.getSelectedItem().toString(),jComboColor.getSelectedItem().toString());
                List<Zapato> zapatos = zapatoDao.busquedaAvanzada(zapatoAd);
                zapatos.forEach(consulta -> {
                    String[] fila = {"" + consulta.getIdProducto(), "" + consulta.getTipo(), "" + consulta.getTalla(), "" + consulta.getColor(), "" + consulta.getMarca(),
                        "" + consulta.getPrecio(), "" + consulta.getCantidad()};
                    modelo.addRow(fila);
                });
                
                break;

            case "Camisas":
                CamisaDao camisaDao = new CamisaDaoJdbc();
                Camisa camisaAd = new Camisa(jComboTipo.getSelectedItem().toString(),jComboTalla.getSelectedItem().toString(),jComboColor.getSelectedItem().toString());
                List<Camisa> camisas = camisaDao.busquedaAvanzada(camisaAd);
                camisas.forEach(consulta -> {
                    String[] fila = {"" + consulta.getIdProducto(), "" + consulta.getTipo(), "" + consulta.getTalla(), "" + consulta.getColor(), "" + consulta.getMarca(),
                        "" + consulta.getPrecio(), "" + consulta.getCantidad()};
                    modelo.addRow(fila);
                });
                break;

            case "Pantalones":
                PantalonDao pantalonDao = new PantalonDaoJdbc();
                Pantalon pantalonAd = new Pantalon(jComboTipo.getSelectedItem().toString(),jComboTalla.getSelectedItem().toString(),jComboColor.getSelectedItem().toString());
                List<Pantalon> pantalones = pantalonDao.busquedaAvanzada(pantalonAd);
                pantalones.forEach(consulta -> {
                    String[] fila = {"" + consulta.getIdProducto(), "" + consulta.getTipo(), "" + consulta.getTalla(), "" + consulta.getColor(), "" + consulta.getMarca(),
                        "" + consulta.getPrecio(), "" + consulta.getCantidad()};
                    modelo.addRow(fila);
                });
                break;

            default:
                if(modelo.getRowCount() != 0)
                JOptionPane.showMessageDialog(null, "No se encontro coincidencia con los datos de la busqueda en la base de datos");
        }
    }//GEN-LAST:event_busquedaAvanzadaActionPerformed

    private void jComboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoActionPerformed


    }//GEN-LAST:event_jComboTipoActionPerformed

    private void jComboTallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTallaActionPerformed

    private void jrZapatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrZapatosActionPerformed
        jComboTipo.removeAllItems();
        jComboTalla.removeAllItems();
        jComboColor.removeAllItems();
        jComboTipo.addItem("mocasin");
        jComboTipo.addItem("tenis");
        jComboTipo.addItem("bota");
        jComboTalla.addItem("38");
        jComboTalla.addItem("39");
        jComboTalla.addItem("40");
        jComboTalla.addItem("41");
        jComboColor.addItem("blanco");
        jComboColor.addItem("negro");
        jComboColor.addItem("verde");
        jComboColor.addItem("amarillo");


    }//GEN-LAST:event_jrZapatosActionPerformed

    private void jrCamisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrCamisasActionPerformed
        jComboTipo.removeAllItems();
        jComboTalla.removeAllItems();
        jComboColor.removeAllItems();
        jComboTipo.addItem("camisa");
        jComboTipo.addItem("polo");
        jComboTalla.addItem("S");
        jComboTalla.addItem("M");
        jComboTalla.addItem("L");
        jComboTalla.addItem("X");
        jComboColor.addItem("blanco");
        jComboColor.addItem("negro");
        jComboColor.addItem("rojo");
        jComboColor.addItem("rosado");
        jComboColor.addItem("beige");
    }//GEN-LAST:event_jrCamisasActionPerformed

    private void jrPantalonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrPantalonesActionPerformed
        jComboTipo.removeAllItems();
        jComboTalla.removeAllItems();
        jComboColor.removeAllItems();
        jComboTipo.addItem("jean");
        jComboTipo.addItem("sudadera");
        jComboTipo.addItem("dril");
        jComboTalla.addItem("32");
        jComboTalla.addItem("34");
        jComboTalla.addItem("36");
        jComboTalla.addItem("40");
        jComboColor.addItem("verde");
        jComboColor.addItem("negro");
        jComboColor.addItem("rojo");

    }//GEN-LAST:event_jrPantalonesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton busquedaAvanzada;
    private javax.swing.JButton consulta;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.JComboBox<String> jCombo;
    private javax.swing.JComboBox<String> jComboColor;
    private javax.swing.JComboBox<String> jComboTalla;
    private javax.swing.JComboBox<String> jComboTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTable jProductos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrCamisas;
    private javax.swing.JRadioButton jrPantalones;
    private javax.swing.JRadioButton jrZapatos;
    // End of variables declaration//GEN-END:variables
}
